const USERS_LIST_REQUEST = 'USERS_LIST_REQUEST';
const USERS_LIST_SUCCESS = 'USERS_LIST_SUCCESS';
const USERS_LIST_FAILURE = 'USERS_LIST_FAILURE';
const USERS_ADD_SUCCESS = 'USERS_ADD_SUCCESS';
const USERS_ADD_FAILURE = 'USERS_ADD_FAILURE';
const USERS_ADD_REQUEST = 'USERS_ADD_REQUEST';


const types = {
    USERS_LIST_REQUEST,
    USERS_LIST_FAILURE,
    USERS_LIST_SUCCESS,
    USERS_ADD_SUCCESS,
    USERS_ADD_FAILURE,
    USERS_ADD_REQUEST

};

export default types;