const USERS_LIST_REQUEST = 'USERS_LIST_REQUEST';
const USERS_LIST_SUCCESS = 'USERS_LIST_SUCCESS';
const USERS_LIST_FAILURE = 'USERS_LIST_FAILURE';
const USERS_ADD_SUCCESS = 'USERS_ADD_SUCCESS';
const USERS_ADD_FAILURE = 'USERS_ADD_FAILURE';
const USERS_ADD_REQUEST = 'USERS_ADD_REQUEST';
const USERS_DELETE_SUCCESS = 'USERS_DELETE_SUCCESS';
const USERS_DELETE_FAILURE = 'USERS_DELETE_FAILURE';
const USERS_DELETE_REQUEST = 'USERS_DELETE_REQUEST';
const USERS_EDIT_SUCCESS = 'USERS_EDIT_SUCCESS';
const USERS_EDIT_FAILURE = 'USERS_EDIT_FAILURE';
const USERS_EDIT_REQUEST = 'USERS_EDIT_REQUEST';


const types = {
    USERS_LIST_REQUEST,
    USERS_LIST_FAILURE,
    USERS_LIST_SUCCESS,
    USERS_ADD_SUCCESS,
    USERS_ADD_FAILURE,
    USERS_ADD_REQUEST,
    USERS_DELETE_SUCCESS,
    USERS_DELETE_FAILURE,
    USERS_DELETE_REQUEST,
    USERS_EDIT_SUCCESS,
    USERS_EDIT_FAILURE,
    USERS_EDIT_REQUEST
};

export default types;