const LIKES_LIST_REQUEST = 'LIKES_LIST_REQUEST';
const LIKES_LIST_SUCCESS = 'LIKES_LIST_SUCCESS';
const LIKES_LIST_FAILURE = 'LIKES_LIST_FAILURE';
const LIKES_ADD_SUCCESS = 'LIKES_ADD_SUCCESS';
const LIKES_ADD_FAILURE = 'LIKES_ADD_FAILURE';
const LIKES_ADD_REQUEST = 'LIKES_ADD_REQUEST';
const LIKES_EDIT_SUCCESS = 'LIKES_EDIT_SUCCESS';
const LIKES_EDIT_FAILURE = 'LIKES_EDIT_FAILURE';
const LIKES_EDIT_REQUEST = 'LIKES_EDIT_REQUEST';
const LIKES_DELETE_SUCCESS = 'LIKES_DELETE_SUCCESS';
const LIKES_DELETE_FAILURE = 'LIKES_DELETE_FAILURE';
const LIKES_DELETE_REQUEST = 'LIKES_DELETE_REQUEST';

const types = {
    LIKES_LIST_REQUEST,
    LIKES_LIST_FAILURE,
    LIKES_LIST_SUCCESS,
    LIKES_ADD_SUCCESS,
    LIKES_ADD_FAILURE,
    LIKES_ADD_REQUEST,
    LIKES_EDIT_SUCCESS,
    LIKES_EDIT_FAILURE,
    LIKES_EDIT_REQUEST,
    LIKES_DELETE_SUCCESS,
    LIKES_DELETE_FAILURE,
    LIKES_DELETE_REQUEST


    

};

export default types;