const POSTS_LIST_REQUEST = 'POSTS_LIST_REQUEST';
const POSTS_LIST_SUCCESS = 'POSTS_LIST_SUCCESS';
const POSTS_LIST_FAILURE = 'POSTS_LIST_FAILURE';
const POSTS_ADD_SUCCESS = 'POSTS_ADD_SUCCESS';
const POSTS_ADD_FAILURE = 'POSTS_ADD_FAILURE';
const POSTS_ADD_REQUEST = 'POSTS_ADD_REQUEST';


const types = {
    POSTS_LIST_REQUEST,
    POSTS_LIST_FAILURE,
    POSTS_LIST_SUCCESS,
    POSTS_ADD_SUCCESS,
    POSTS_ADD_FAILURE,
    POSTS_ADD_REQUEST

};

export default types;