const POSTS_LIST_REQUEST = 'POSTS_LIST_REQUEST';
const POSTS_LIST_SUCCESS = 'POSTS_LIST_SUCCESS';
const POSTS_LIST_FAILURE = 'POSTS_LIST_FAILURE';
const POSTS_ADD_SUCCESS = 'POSTS_ADD_SUCCESS';
const POSTS_ADD_FAILURE = 'POSTS_ADD_FAILURE';
const POSTS_ADD_REQUEST = 'POSTS_ADD_REQUEST';
const POSTS_DELETE_SUCCESS = 'POSTS_DELETE_SUCCESS';
const POSTS_DELETE_FAILURE = 'POSTS_DELETE_FAILURE';
const POSTS_DELETE_REQUEST = 'POSTS_DELETE_REQUEST';
const POSTS_EDIT_SUCCESS = 'POSTS_EDIT_SUCCESS';
const POSTS_EDIT_FAILURE = 'POSTS_EDIT_FAILURE';
const POSTS_EDIT_REQUEST = 'POSTS_EDIT_REQUEST';



const types = {
    POSTS_LIST_REQUEST,
    POSTS_LIST_FAILURE,
    POSTS_LIST_SUCCESS,
    POSTS_ADD_SUCCESS,
    POSTS_ADD_FAILURE,
    POSTS_ADD_REQUEST,
    POSTS_DELETE_SUCCESS,
    POSTS_DELETE_FAILURE,
    POSTS_DELETE_REQUEST,
    POSTS_EDIT_SUCCESS,
    POSTS_EDIT_FAILURE,
    POSTS_EDIT_REQUEST

};

export default types;

