const COMMENTS_LIST_REQUEST = 'COMMENTS_LIST_REQUEST';
const COMMENTS_LIST_SUCCESS = 'COMMENTS_LIST_SUCCESS';
const COMMENTS_LIST_FAILURE = 'COMMENTS_LIST_FAILURE';
const COMMENTS_ADD_SUCCESS = 'COMMENTS_ADD_SUCCESS';
const COMMENTS_ADD_FAILURE = 'COMMENTS_ADD_FAILURE';
const COMMENTS_ADD_REQUEST = 'COMMENTS_ADD_REQUEST';


const types = {
    COMMENTS_LIST_REQUEST,
    COMMENTS_LIST_FAILURE,
    COMMENTS_LIST_SUCCESS,
    COMMENTS_ADD_SUCCESS,
    COMMENTS_ADD_FAILURE,
    COMMENTS_ADD_REQUEST

};

export default types;